### ISSUE TITLE
"Hello\r\n World" does not round-trip

### ISSUE THREAD

**Issue by jamietwells** [aaubry/YamlDotNet#670]
See demonstration:

https://dotnetfiddle.net/RZBJru

Input: 

```
Hello
 World
```

yaml:

```
WindowsTrailingWhitespace: >-
  Hello

   World
```

Output:

```
Hello

 World
```

Expected output:

```
Hello
 World
```

Expected yaml:

```
WindowsTrailingWhitespace: >-
  Hello
   World
```

**Comment by jamietwells** [comment]
I just tired to fix this but it looks like this is already fixed in https://github.com/aaubry/YamlDotNet/pull/626

When is the version with this fix included being released?

**Comment by EdwardCooke** [comment]
We're working on getting a new release out soon.

**Comment by EdwardCooke** [comment]
The output yaml is still incorrect, it includes the middle whitespace line. Once my previous pull request gets merged in I'll start work on this.

**Comment by EdwardCooke** [comment]
Git failed me. It's working on a fresh clone of the master branch. Closing this issue. If you see the problem still there after next release, feel free to re-open it.
